Remove dietpi_nix_daemon
Give root@manjaro an authorised key for pi@dietpi.local without a passphrase. In
the future we may tighten this up by restricting it to a locked-down nix user on
the DietPi, rather than a full user like pi.

The reason I'm getting rid of dietpi_nix_daemon is that it can be unreliable,
with weird communication errors, e.g.

```
nix copy -vv --from 'unix:///tmp/dietpi-nix-daemon.sock' '/nix/store/h8jw4j0yfxsn3nlmmbwd3903jbggn3f9-panpipe-0.4.1.0-doc'
copying 1 paths...
copying path '/nix/store/h8jw4j0yfxsn3nlmmbwd3903jbggn3f9-panpipe-0.4.1.0-doc' from 'unix:///tmp/dietpi-nix-daemon.sock'...
error (ignored): error: reached end of FramedSource
error: getting status of
'/nix/store/h8jw4j0yfxsn3nlmmbwd3903jbggn3f9-panpipe-0.4.1.0-doc': No such file
or directory
```